---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: infra-jenkins
roleRef:
  kind: Role
  name: jenkins-secret-reader
  apiGroup: rbac.authorization.k8s.io
