apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  valuesFile: values.yaml
  includeCRDs: true
namespace: infra-ingress
